In [1]:
import numpy as np

In [2]:
array_1 = np.array([10.4519029313, 89.12391238123])

In [3]:
array_1

array([10.45190293, 89.12391238])

In [4]:
# Truncating Array
trunc_array = np.trunc(array_1)
trunc_array

array([10., 89.])

In [10]:
# Rounding the Values
rounded_array = np.round(array_1, 1) # pass the number of points as second parameter
rounded_array

array([10.5, 89.1])

In [12]:
# Floor and Ceiling
floor_array = np.floor(array_1)
ceil_array = np.ceil(array_1)

display(array_1)
display(floor_array)
ceil_array

array([10.45190293, 89.12391238])

array([10., 89.])

array([11., 90.])

In [18]:
# Zeros
zeros_array = np.zeros(4)
reshaped_array = np.reshape(zeros_array, (2, 2))

display(reshaped_array)
zeros_array

array([[0., 0.],
       [0., 0.]])

array([0., 0., 0., 0.])

In [23]:
# Identity Matrix
identity_matrix = np.eye(4)
identity_matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
# Ufunc (Universal Functions)
# add, subtract, multiply, division

array_1 = np.array([1, 2, 3, 4])
array_2 = np.array([5, 6, 7, 8])

np.add(array_1, array_2)

array([ 6,  8, 10, 12])

In [25]:
array_1 = np.array([10, 20, 30, 40, 50])
np.add.reduce(array_1)

np.int64(150)

In [29]:
array_1 = np.array([20, 36, 24])

display(np.lcm.reduce(array_1))
np.gcd.reduce(array_1)

np.int64(360)

np.int64(4)

In [30]:
# Filtering and Applying Function

array_1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [33]:
condition = array_1 % 2 == 0
even_array = array_1[condition]
odd_array = array_1[~condition] # Applying Not to the filter

display(even_array)
display(odd_array)

array([ 2,  4,  6,  8, 10])

array([1, 3, 5, 7, 9])

In [35]:
# get the only elements that are greater than 5
condition = array_1 >= 5
greater_than_5 = array_1[condition]
greater_than_5

array([ 5,  6,  7,  8,  9, 10])

In [36]:
condition = array_1 < 6
np.where(condition) # same to array_1[condition]

(array([0, 1, 2, 3, 4]),)

In [42]:
# Conditional Changes
# Multiply the odd numbers by 2 and do not change the even values
condition = array_1 % 2 == 0

# Format of parameters (condition, value_if_true, value_if_false)
new_array = np.where(condition, array_1 * 3, array_1 * 2)

display(array_1)
new_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

array([ 2,  6,  6, 12, 10, 18, 14, 24, 18, 30])

In [ ]:
# Use np.random.randint(40, 100, size=(6, 4)) to create a grade matrix.
# Create an identity matrix using np.eye(4) to represent equal weightage across 4 subjects.
# Multiply the grade matrix with the identity matrix (no effect, but demonstrates matrix operations).
# Use np.add.reduce() to compute each student’s total marks.
# Find each student’s average marks using np.mean() (ufunc concept).
# Sort the students by their total marks using np.sort() and np.argsort().
# Display top 3 students with their total and average marks.