In [1]:
# arange - Automatic Range
import numpy as np

In [2]:
# Start, Stop, Step
array_1 = np.arange(10)

In [3]:
array_1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array_2 = np.arange(10, 41, 5)

In [7]:
array_2

array([10, 15, 20, 25, 30, 35, 40])

In [8]:
array_3 = np.arange(100, 10, -10)
array_3

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [9]:
# Ordering or Sorting
array_3 = np.sort(array_3)
array_3

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100])

In [10]:
# List Indexing and Slicing for reverse sorting (descending)

array_3 = array_3[::-1]
array_3

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [42]:
# Sort a two dimensional array
array_2d = np.array([[45, 34, 42], [89, 91, 44], [65, 42, 33]])

In [43]:
array_2d = np.sort(array_2d, axis=1) # axis=0 for column and axis=1 for row
array_2d

array([[34, 42, 45],
       [44, 89, 91],
       [33, 42, 65]])

In [13]:
array_2d.ndim

2

In [14]:
array_2d.shape

(3, 3)

In [44]:
array_2d_reverse = array_2d[:, ::-1]
array_2d_reverse

array([[45, 42, 34],
       [91, 89, 44],
       [65, 42, 33]])

In [46]:
# Concatenation - Joining two different arrays

# Parameter is a tuple
arrays_to_concat = (array_2d, array_2d_reverse)

# Pass the tuple as a parameter to the concat method
array_concat = np.concat(arrays_to_concat)

In [47]:
array_concat

array([[34, 42, 45],
       [44, 89, 91],
       [33, 42, 65],
       [45, 42, 34],
       [91, 89, 44],
       [65, 42, 33]])

In [50]:
# Reshape - To change the dimension
# 1d array [10, 20, 30, 40, 50, 60]
# 2d array [
#     [10, 20, 30],
#     [40, 50, 60]
#     ]

array_1 = np.arange(10, 101, 10)

In [51]:
array_1.shape

(10,)

In [52]:
# Convert (10,) to (5,2)
array_converted = np.reshape(array_1, (5, 2))

In [53]:
display(array_converted)
array_converted.shape

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

(5, 2)

In [ ]:
# Make a (20,) array using arange
# Convert to a 3 dimensional array
# Sort the array
# Sort the array in reverse
# Concat the two sorted arrays

In [54]:
array_1d = np.arange(1, 21)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [55]:
array_1d.shape

(20,)

In [56]:
array_reshaped = np.reshape(array_1d, (5, 2, 2))

In [57]:
array_reshaped

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20]]])

In [58]:
array_reshaped_reverse = array_reshaped[:, :, ::-1]

In [59]:
array_reshaped_reverse

array([[[ 2,  1],
        [ 4,  3]],

       [[ 6,  5],
        [ 8,  7]],

       [[10,  9],
        [12, 11]],

       [[14, 13],
        [16, 15]],

       [[18, 17],
        [20, 19]]])

In [62]:
array_concatenated = np.concat((array_reshaped, array_reshaped_reverse), axis=2)
array_concatenated

array([[[ 1,  2,  2,  1],
        [ 3,  4,  4,  3]],

       [[ 5,  6,  6,  5],
        [ 7,  8,  8,  7]],

       [[ 9, 10, 10,  9],
        [11, 12, 12, 11]],

       [[13, 14, 14, 13],
        [15, 16, 16, 15]],

       [[17, 18, 18, 17],
        [19, 20, 20, 19]]])

In [64]:
array_split = np.split(array_1d, 2)

In [65]:
array_split

[array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]),
 array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])]