In [1]:
# Creating an array with random elements
import numpy as np

In [16]:
# Minimum value, Maximum Value, Size of array
random_array = np.random.randint(10, 50, size=(5, 4))
random_array

array([[14, 14, 21, 18],
       [23, 46, 27, 19],
       [24, 36, 30, 18],
       [14, 49, 19, 35],
       [19, 48, 43, 10]])

In [17]:
# Sort the array
np.sort(random_array, axis=1)

array([[14, 14, 18, 21],
       [19, 23, 27, 46],
       [18, 24, 30, 36],
       [14, 19, 35, 49],
       [10, 19, 43, 48]])

In [22]:
# Array Operations
random_array_1 = np.random.randint(10, 100, size=(4,4))
random_array_2 = np.random.randint(10, 100, size=(4,4))

random_array_1, random_array_2

(array([[10, 84, 82, 91],
        [95, 66, 81, 64],
        [55, 16, 84, 64],
        [95, 91, 52, 35]]),
 array([[25, 84, 97, 86],
        [96, 81, 75, 83],
        [94, 73, 23, 73],
        [25, 11, 51, 69]]))

In [19]:
# Addition
addition_array = random_array_1 + random_array_2 + random_array_1
addition_array

array([[ 53, 130, 161, 125],
       [124, 104, 118,  82],
       [139,  34,  91, 163],
       [136, 127, 143, 182]])

In [28]:
addition_array = np.add(random_array_1, random_array_2)
addition_array

array([[ 35, 168, 179, 177],
       [191, 147, 156, 147],
       [149,  89, 107, 137],
       [120, 102, 103, 104]])

In [ ]:
# np.subtract | -
# np.multiply | *
# np.divide | /
# np.divmod | %

In [24]:
multiply_array = random_array_1 * random_array_2
multiply_array

array([[ 250, 7056, 7954, 7826],
       [9120, 5346, 6075, 5312],
       [5170, 1168, 1932, 4672],
       [2375, 1001, 2652, 2415]])

In [25]:
division_array = random_array_1 / random_array_2
division_array

array([[0.4       , 1.        , 0.84536082, 1.05813953],
       [0.98958333, 0.81481481, 1.08      , 0.77108434],
       [0.58510638, 0.21917808, 3.65217391, 0.87671233],
       [3.8       , 8.27272727, 1.01960784, 0.50724638]])

In [30]:
divmod_array = random_array_1 % random_array_2
display(random_array_1)
display(random_array_2)
divmod_array

array([[10, 84, 82, 91],
       [95, 66, 81, 64],
       [55, 16, 84, 64],
       [95, 91, 52, 35]])

array([[25, 84, 97, 86],
       [96, 81, 75, 83],
       [94, 73, 23, 73],
       [25, 11, 51, 69]])

array([[10,  0, 82,  5],
       [95, 66,  6, 64],
       [55, 16, 15, 64],
       [20,  3,  1, 35]])

In [49]:
# Float Types Array
random_array = 100 * np.random.rand(5, 4) # Change the value to a range of 0 to 100
random_array

array([[90.51113657, 81.20717307,  4.05989863, 66.70719604],
       [29.87577276, 47.71302859, 44.58586767, 16.9552147 ],
       [48.54272186,  3.1091798 , 13.98220081, 89.06817086],
       [73.06097551, 34.6297424 ,  9.81040415, 23.12842071],
       [93.2804174 , 22.81540016,  6.95017777, 41.62608688]])

In [ ]:
# Task: Generate a random array of integers of 4 dimension and Generate another random array 
# of floats of 4 dimension and then perform operations: add, multiply, division
# Reshape the sum array to 2 dimensions, product array to 3 dimensions and division array to 1 dimension
# Sort sum array in descending order, product array in ascending order, division array in descending order
# Reshape sorted division array to 2 dimensions and concat the sorted sum array and reshaped division array

In [54]:
integer_arr = np.random.randint(10, 100, size=(3, 2, 2, 5))
float_arr = 100 * np.random.rand(3, 2, 2, 5)

display(integer_arr)
float_arr

array([[[[61, 86, 92, 83, 54],
         [13, 37, 95, 58, 76]],

        [[51, 76, 51, 82, 83],
         [15, 16, 67, 71, 74]]],


       [[[56, 52, 17, 11, 79],
         [43, 62, 69, 25, 73]],

        [[47, 99, 45, 58, 73],
         [10, 70, 38, 81, 72]]],


       [[[18, 20, 13, 11, 64],
         [96, 80, 59, 54, 19]],

        [[84, 81, 59, 51, 97],
         [63, 81, 28, 89, 42]]]])

array([[[[ 1.64253337,  7.17377377, 82.91821114, 45.5946238 ,
           5.40654311],
         [43.46074012, 36.65112938, 18.26050124, 74.65113144,
          37.05692161]],

        [[ 3.17092945, 33.20155334, 89.58941348, 81.56667875,
          70.41093415],
         [86.20669541, 99.26642653, 74.55937772, 83.49021139,
          90.31110951]]],


       [[[97.3326666 , 34.95799959, 88.54663748,  9.45194768,
          92.11088159],
         [16.82127262, 78.01528097, 68.2713521 , 34.0296586 ,
          78.97037258]],

        [[78.46875903, 33.31257881, 95.04837568, 69.11558754,
          54.04749904],
         [22.06014853, 39.48529573,  8.32101609, 99.25537344,
          29.06583411]]],


       [[[96.69127773, 73.27245238, 49.47003761, 28.83006341,
          46.98906606],
         [70.60786097, 45.76534806, 48.31949909, 24.79640955,
          24.20354467]],

        [[44.92956472, 35.99633662, 39.31200996, 46.81298516,
          77.06468786],
         [ 4.35708156,  7.64021244, 70.1

In [55]:
addition = integer_arr + float_arr
multiply = integer_arr * float_arr
division = integer_arr / float_arr

addition, multiply, division

(array([[[[ 62.64253337,  93.17377377, 174.91821114, 128.5946238 ,
            59.40654311],
          [ 56.46074012,  73.65112938, 113.26050124, 132.65113144,
           113.05692161]],
 
         [[ 54.17092945, 109.20155334, 140.58941348, 163.56667875,
           153.41093415],
          [101.20669541, 115.26642653, 141.55937772, 154.49021139,
           164.31110951]]],
 
 
        [[[153.3326666 ,  86.95799959, 105.54663748,  20.45194768,
           171.11088159],
          [ 59.82127262, 140.01528097, 137.2713521 ,  59.0296586 ,
           151.97037258]],
 
         [[125.46875903, 132.31257881, 140.04837568, 127.11558754,
           127.04749904],
          [ 32.06014853, 109.48529573,  46.32101609, 180.25537344,
           101.06583411]]],
 
 
        [[[114.69127773,  93.27245238,  62.47003761,  39.83006341,
           110.98906606],
          [166.60786097, 125.76534806, 107.31949909,  78.79640955,
            43.20354467]],
 
         [[128.92956472, 116.99633662,  98.312009

In [57]:
addition = np.reshape(addition, (6, 10))
multiply = np.reshape(multiply, (4, 5, 3))
division = np.reshape(division, (60,))

addition, multiply, division

(array([[ 62.64253337,  93.17377377, 174.91821114, 128.5946238 ,
          59.40654311,  56.46074012,  73.65112938, 113.26050124,
         132.65113144, 113.05692161],
        [ 54.17092945, 109.20155334, 140.58941348, 163.56667875,
         153.41093415, 101.20669541, 115.26642653, 141.55937772,
         154.49021139, 164.31110951],
        [153.3326666 ,  86.95799959, 105.54663748,  20.45194768,
         171.11088159,  59.82127262, 140.01528097, 137.2713521 ,
          59.0296586 , 151.97037258],
        [125.46875903, 132.31257881, 140.04837568, 127.11558754,
         127.04749904,  32.06014853, 109.48529573,  46.32101609,
         180.25537344, 101.06583411],
        [114.69127773,  93.27245238,  62.47003761,  39.83006341,
         110.98906606, 166.60786097, 125.76534806, 107.31949909,
          78.79640955,  43.20354467],
        [128.92956472, 116.99633662,  98.31200996,  97.81298516,
         174.06468786,  67.35708156,  88.64021244,  98.19259022,
         173.58763877, 126.943

In [59]:
addition.shape, multiply.shape, division.shape

((6, 10), (4, 5, 3), (60,))

In [61]:
addition = np.sort(addition, axis=1)[:, ::-1]
multiply = np.sort(multiply, axis=2)
division = np.sort(division)[::-1]

addition, multiply, division

(array([[174.91821114, 132.65113144, 128.5946238 , 113.26050124,
         113.05692161,  93.17377377,  73.65112938,  62.64253337,
          59.40654311,  56.46074012],
        [164.31110951, 163.56667875, 154.49021139, 153.41093415,
         141.55937772, 140.58941348, 115.26642653, 109.20155334,
         101.20669541,  54.17092945],
        [171.11088159, 153.3326666 , 151.97037258, 140.01528097,
         137.2713521 , 105.54663748,  86.95799959,  59.82127262,
          59.0296586 ,  20.45194768],
        [180.25537344, 140.04837568, 132.31257881, 127.11558754,
         127.04749904, 125.46875903, 109.48529573, 101.06583411,
          46.32101609,  32.06014853],
        [166.60786097, 125.76534806, 114.69127773, 110.98906606,
         107.31949909,  93.27245238,  78.79640955,  62.47003761,
          43.20354467,  39.83006341],
        [174.06468786, 173.58763877, 128.92956472, 126.94376812,
         116.99633662,  98.31200996,  98.19259022,  97.81298516,
          88.64021244,  67.357

In [62]:
division = np.reshape(division, (6, 10))
division

array([[37.13775376, 16.08361233, 14.45921981, 11.98811152, 10.60179944,
         9.98789779,  5.20248589,  4.56674997,  2.97185038,  2.55628697],
       [ 2.47713517,  2.28904953,  2.25022898,  2.17773464,  2.05089891,
         1.86959301,  1.82039006,  1.77281185,  1.74804745,  1.50081362],
       [ 1.4874993 ,  1.36201898,  1.35962198,  1.35066379,  1.25868284,
         1.22103915,  1.17879419,  1.1637813 ,  1.10952707,  1.08944131],
       [ 1.05216319,  1.01067282,  1.00951869,  1.00531248,  0.92439731,
         0.89861265,  0.85766197,  0.85039909,  0.83917394,  0.81938978],
       [ 0.81607672,  0.7947161 ,  0.78500898,  0.77694737,  0.73465327,
         0.59896449,  0.57534641,  0.56926369,  0.49444475,  0.47344312],
       [ 0.4533061 ,  0.3989025 ,  0.38154616,  0.29912054,  0.27295388,
         0.26278533,  0.19198922,  0.1861595 ,  0.17400041,  0.16118239]])

In [63]:
concat_arr = np.concat((addition, division), axis=1)

In [64]:
concat_arr

array([[1.74918211e+02, 1.32651131e+02, 1.28594624e+02, 1.13260501e+02,
        1.13056922e+02, 9.31737738e+01, 7.36511294e+01, 6.26425334e+01,
        5.94065431e+01, 5.64607401e+01, 3.71377538e+01, 1.60836123e+01,
        1.44592198e+01, 1.19881115e+01, 1.06017994e+01, 9.98789779e+00,
        5.20248589e+00, 4.56674997e+00, 2.97185038e+00, 2.55628697e+00],
       [1.64311110e+02, 1.63566679e+02, 1.54490211e+02, 1.53410934e+02,
        1.41559378e+02, 1.40589413e+02, 1.15266427e+02, 1.09201553e+02,
        1.01206695e+02, 5.41709294e+01, 2.47713517e+00, 2.28904953e+00,
        2.25022898e+00, 2.17773464e+00, 2.05089891e+00, 1.86959301e+00,
        1.82039006e+00, 1.77281185e+00, 1.74804745e+00, 1.50081362e+00],
       [1.71110882e+02, 1.53332667e+02, 1.51970373e+02, 1.40015281e+02,
        1.37271352e+02, 1.05546637e+02, 8.69579996e+01, 5.98212726e+01,
        5.90296586e+01, 2.04519477e+01, 1.48749930e+00, 1.36201898e+00,
        1.35962198e+00, 1.35066379e+00, 1.25868284e+00, 1.2210

In [65]:
concat_arr.shape

(6, 20)